fits/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^my_workouts/$', views.my_workouts, name='my_workouts'),
    url(r'^workout/(?P<workout_id>\d+)/$', views.workout, name='workout'),
    url(r'^add_workout/$', views.add_workout, name='add_workout'),
    url(r'^edit_workout/(?P<workout_id>\d+)/$', views.edit_workout, name='edit_workout'),
    url(r'^goal', views.goal, name='goal'),
    url(r'^add_goal/$', views.add_goal, name='add_goal'),
    url(r'^edit_goal/$', views.edit_goal, name='edit_goal'),
    url(r'^weight/$', views.weight, name='my_weight'),
    url(r'^add_weight/$', views.add_weight, name='add_weight'),
]

i_am_fit/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include("fits.urls", namespace='fits')),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register')
]

fits/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Goal(models.Model):
    goal_type = (
        ('ls', 'loose weight'),
        ('ms', 'build a mass'),
        ('ft', 'fit lifestyle'),
        ('ot', 'other')
    )
    # goal = models.CharField(max_length='2', choices=goal_type)
    goal = models.CharField(max_length=300)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __unicode__(self):
        return self.goal

    def __str__(self):
        return self.goal


class Workout(models.Model):
    workout_type = (
        ('fit', 'Fitness'),
        ('car', 'Cardio'),
        ('str', 'Strength training')
    )
    text = models.CharField(max_length=3, choices=workout_type)
    date_added = models.DateTimeField(auto_now_add=True)
    date_workout = models.DateTimeField()
    duration = models.IntegerField()
    owner = models.ForeignKey(User)

    def workout_type(self):
        return self.get_workout_type_display()

    def __unicode__(self):
        return unicode(self.date_workout.strftime('%d-%m-%Y'))


class Weight(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)
    value = models.FloatField()

    def __str__(self):
        return str(self.value)

fits/forms.py
from django import forms

from .models import Workout, Goal, Weight


class DateTimeInput(forms.DateTimeInput):
    input_type = 'date'


class WorkoutForm(forms.ModelForm):
    class Meta:
        model = Workout
        fields = ['text', 'date_workout', 'duration']
        widgets = {'date_workout': DateTimeInput()}
        labels = {'text': 'Kind of workout', 'date_workout': 'Date of workout', 'duration': 'duration (in minutes)'}


class GoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        fields = ['goal']
        labels = {'goal': 'My goal'}


class WeightForm(forms.ModelForm):
    class Meta:
        model = Weight
        fields = ['value']
        labels = {'value': 'My current weight'}

fits/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Workout, Goal, Weight
from .forms import WorkoutForm, GoalForm, WeightForm


def index(request):
    """Main page"""
    if request.user.is_authenticated() and Goal.objects.filter(owner=request.user):
        goals = Goal.objects.filter(owner=request.user).order_by('date_added')
        context = {'goal': goals[0]}
    else:
        context = {'goal': "Goal isn't added yet."}
    return render(request, 'fits/index.html', context)


@login_required
def my_workouts(request):
    my_workouts = Workout.objects.filter(owner=request.user).order_by('-date_workout')
    context = {'my_workouts': my_workouts}
    return render(request, 'fits/my_workouts.html', context)


@login_required
def workout(request, workout_id):
    workout = Workout.objects.get(id=workout_id)
    context = {'workout': workout}
    return render(request, 'fits/workout.html', context)


@login_required
def add_workout(request):
    if request.method != "POST":
        form = WorkoutForm()
    else:
        form = WorkoutForm(request.POST)
        if form.is_valid():
            new_workout = form.save(commit=False)
            new_workout.owner = request.user
            new_workout.save()
            return HttpResponseRedirect(reverse('fits:my_workouts'))
    context = {'form': form}
    return render(request, 'fits/add_workout.html', context)


@login_required
def edit_workout(request, workout_id):
    edited_workout = Workout.objects.get(id=workout_id)

    if request.method != 'POST':
        form = WorkoutForm(instance=edited_workout)
    else:
        form = WorkoutForm(instance=edited_workout, data=request.POST)
        if form.is_valid():
            edited_workout = form.save(commit=False)
            edited_workout.owner = request.user
            edited_workout.save()
            return HttpResponseRedirect(reverse('fits:my_workouts'))
    context = {'workout': edited_workout, 'workout_id': workout_id, 'form': form}
    return render(request, 'fits/edit_workout.html', context)


# TODO create a goal
@login_required
def goal(request):
    if Goal.objects.filter(owner=request.user):
        goals = Goal.objects.filter(owner=request.user).order_by('date_added')
        context = {'goal': goals[0]}
    else:
        context = {'goal': ''}
        # context = {'goal': "Goal isn't added yet."}
    return render(request, 'fits/goal.html', context)


@login_required
def add_goal(request):
    if request.method != "POST":
        form = GoalForm()
    else:
        form = GoalForm(request.POST)
        if form.is_valid():
            goal = form.save(commit=False)
            goal.owner = request.user
            goal.save()
            return HttpResponseRedirect(reverse('fits:goal'))
    context = {'form': form}
    return render(request, 'fits/add_goal.html', context)


@login_required
def edit_goal(request):
    goal = Goal.objects.filter(owner=request.user).order_by('date_added')[0]
    if request.method != 'POST':
        form = GoalForm(instance=goal)
    else:
        form = GoalForm(instance=goal, data=request.POST)
        if form.is_valid():
            goal = form.save(commit=False)
            goal.owner = request.user
            goal.save()
            return HttpResponseRedirect(reverse('fits:goal'))
    context = {'goal': goal, 'form': form}
    return render(request, 'fits/edit_goal.html', context)


@login_required
def weight(request):
    my_weight = Weight.objects.filter(owner=request.user).order_by('-date_added')
    weights_list = []
    dates_list = []
    for weights in my_weight:
        weights_list.append(weights.value)
        dates_list.append(weights.date_added.strftime('%Y-%m-%d'))
    context = {'my_weight': weights_list, 'my_weight_dates_added': dates_list}
    return render(request, 'fits/my_weight.html', context)


@login_required
def add_weight(request):
    if request.method != "POST":
        form = WeightForm()
    else:
        form = WeightForm(request.POST)
        if form.is_valid():
            new_weight = form.save(commit=False)
            new_weight.owner = request.user
            new_weight.save()
            return HttpResponseRedirect(reverse('fits:my_weight'))
    context = {'form': form}
    return render(request, 'fits/add_weight.html', context)

fits/templates/fits/add_goal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My goal</title>
</head>

{% extends 'fits/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h2>Add your goal:</h2>
{% endblock header %}

<body>

{% block content %}

<form action="{% url 'fits:add_goal' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock content %}

</body>
</html>

fits/templates/fits/add_weight.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add weight</title>
</head>
{% extends 'fits/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h2>Add your current weight:</h2>
{% endblock header %}

<body>

{% block content %}

<form action="{% url 'fits:add_weight' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button name="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock content %}

</body>
</html>

fits/templates/fits/add_workout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add workout</title>
</head>

{% extends 'fits/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h2>Add a workout:</h2>
{% endblock header %}

<body>

{% block content %}

<form action="{% url 'fits:add_workout' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock content %}

</body>
</html>

fits/templates/fits/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="'IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>I'm fit</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>
  <body>
  <nav class="navbar navbar-default">
      <div class="container-fluid">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href='{% url "fits:index" %}'>I'am fit!</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li class="active"><a href='{% url "fits:my_workouts" %}'>My workouts <span class="sr-only">(current)</span></a></li>
                  <li class="active"><a href='{% url "fits:goal" %}'>My goal <span class="sr-only">(current)</span></a></li>
                  <li class="active"><a href='{% url "fits:my_weight" %}'>My weight <span class="sr-only">(current)</span></a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                  {% if user.is_authenticated %}
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                          <li><a href="{% url 'users:logout' %}">Logout</a></li>
                          <!-- <li role="separator" class="divider"></li> -->
                      </ul>
                  </li>
                  {% else %}
                  <li><a href="{% url 'users:register' %}">Register</a></li>
                  <li><a href="{% url 'users:login' %}">Login</a></li>
                  {% endif %}
              </ul>
          </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
      <div class="page-header">
          {% block header %}{% endblock header %}
      </div>
      <div>
          {% block extrahead %}{% endblock extrahead %}
      </div>
      <div>
          {% block content %}{% endblock content %}
      </div>
  </div>
  </body>
</html>

fits/templates/fits/edit_goal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change goal</title>
</head>
<body>
{% extends 'fits/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h3>Change the workout:</h3>
{% endblock header %}

{% block content %}
<form action="{% url 'fits:edit_goal' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}

</form>
{% endblock content %}

</body>
</html>

fits/templates/fits/edit_workout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit workout</title>
</head>

{% extends 'fits/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h3>Edit the workout:</h3>
{% endblock header %}

<body>

{% block content %}
<form action="{% url 'fits:edit_workout' workout.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

</body>
</html>

fits/templates/fits/goal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My goal</title>
</head>
{% extends 'fits/base.html' %}

<body>

{% block content %}

{% if goal %}
    <h2>My goal: {{ goal }}</h2>
    <h3><a href="{% url 'fits:edit_goal' %}">Change the goal</a></h3>
{% else %}
    <h2>Goal isn't added yet.</h2>
    <h3><a href="{% url 'fits:add_goal' %}">Add a goal</a></h3>
{% endif %}

{% endblock content %}


</body>
</html>

fits/templates/fits/index.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>I'm fit!</title>
</head>
<body>
    {% extends 'fits/base.html' %}

    {% block header %}
      <div class="jumbotron">
          <h1>
              {% if user.is_authenticated %}
                  My goal: {{ goal }}
              {% else %}
                  Be fit!
              {% endif %}
          </h1>
      </div>
    {% endblock header %}

    {% block content %}
      <h2>
          {% if user.is_authenticated %}
            Hello, {{ user.username }}!
          {% else %}
          I'm fit is used to keep a training diary.
            <a href="{% url 'users:register' %}">Register</a> to use the app I'm fit.
          {% endif %}
      </h2>
    {% endblock content %}
</body>
</html>

fits/templates/fits/my_weight.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My weight</title>
</head>

{% extends 'fits/base.html' %}

{% block extrahead %}
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js" type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
$( document ).ready(function() {
    var chartData = {
        labels: {{ my_weight_dates_added|safe }},
        datasets: [
            {
                label: "My weight",
                fillColor: "rgba(220,220,220,0.2)",
                strokeColor: "rgba(220,220,220,1)",
                pointColor: "rgba(220,220,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: {{ my_weight }}
            }
        ]
    };
    var ctx = document.getElementById("bodyWeightChart").getContext("2d");
    new Chart(ctx).Line(chartData);
});
</script>
{% endblock %}

{% block content %}
  <canvas id="bodyWeightChart" width="500" height="300"></canvas>

  <h3><a href="{% url 'fits:add_weight' %}">Add your actually weight.</a></h3>
{% endblock %}


</html>

fits/templates/fits/my_workouts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My workouts</title>
</head>

{% extends 'fits/base.html' %}

{% block header %}

  <h1>My workouts:</h1>

{% endblock header %}

<body>

{% block content %}
  <ul>
      {% for workout in my_workouts %}
        <li>
            <h3>
                <a href="{% url 'fits:workout' workout.id %}">{{ workout }}</a>
            </h3>
        </li>
      {% empty %}
        <li>You have not added any workout yet.</li>
      {% endfor %}
  </ul>
  <h3><a href="{% url 'fits:add_workout' %}">Add a workout</a></h3>
{% endblock content %}


</body>
</html>

fits/templates/fits/workout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Workout</title>
</head>

{% extends 'fits/base.html' %}

{% block header %}
  <h3>Workout on {{ workout.date_workout }}</h3>
{% endblock header %}

<body>

{% block content %}

  <h3>Type of workout: {{ workout.text }}</h3>
  <h3>Duration of workout: {{ workout.duration }}</h3>
  <h3><a href='{% url "fits:edit_workout" workout.id %}'>Edit the workout</a></h3>

{% endblock content %}

</body>
</html>